language: generic
sudo: required
dist: trusty
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build
- docker-compose up -d
script:
- docker-compose run web typesafety --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
env:
  global:
  - secure: aZU61SflVNAa2JzI16FfLZxjdFVMASVwlmYstY8vTEZV2H0q2yW+fcLZMxmr9SnAoGC5JGuz32wMbeBAJhPAVtUNdyM648R9/Qt1L9rsI0esnBWBw4Q8b1bM8HkK4lEuR3oscLOOvdxGCBCh0SiiOPkgXq4ZkBTstOhQbiAxdCcWIA+F5qYYMKgmSUhP4uarP6Y1XdgPkkMd/0CX/H5pxDmMG+IR0c0Zkj/0lCJRU4cMMlbkUEahsetH//fIqfphXP/wblixPirA4+RwlWFeJnB0TPVarDrNYqJow3d6An5wfl/xtq+KlXzy4pAKovcGdT9bqMlu3eo/m5chhj2hU32ksnPZ2CijaX0971R4nv8I6fDfdAwd7MIIZlxqM4596hGpTxo25ci08uKelWgQI9RrAGIle57GpvgZ40KGP24TvlWUqAEUlvCX0gQcu93wwrfjne0GzboQEmGtO1hozx6wKiiEv21sSkNeKK/sFXuEdHrUqw19jbVoB7P5m/ggMpF7t8Efqavb2x4QJ0rit5uXUeroga7Jygw3sXX+Q6WJNukxNVAZdHtwWtHrfddFEKE6W5+VHxXWCarSvV9bz1JXR9jDzHBxZD8SWHKzkkwpRGPZuC/IX3CKcImI6nr0uuMnV9U7rD+Gb4cFaO6eoymPgExOSqCMA0Few5CtT7Q=
  - secure: fXb/i/Dk5oDM/ucYonDXoEkJHpLp/QAYXvktY+vAfLQqfuAh9WoJknEvbZK7nsvlSSFHOciCCUOlSg9dAn4vvR5aFfkGpzHBgbggr8xhLa9+ptj4JJ+iczSHXgy/TCtUq9EIkOS9yyBFkHI42idtDxeNsCBlKSGMraaXlX3RRhTr0YRWrA8DTEE+ItluaNcnlrTlGypvSnZqvYJVG3crIS0T+Xv4mHXBKQAfU8UlZvenKlGBlGrE/y04W638k3QfkaM+kGMuB1WLwWtUwDnhpkUPB12Tw8nvMfuqeR+ETl6ouhpCcEp8CUgEWWv5X/7HdscbitwK6SVAvqbWrDA2LNvaKqauPHqwZVUl9+/1bDeEE6rd2zb0LU2jw99htjHVXQoPkbBeZKYLb97+Q1KDWN9gKEQkk6Prd76k80jamNronnmIBrBIp70R5r9jTWuZhu18Qufb29KqdWYI8pX4EBip82aGh2qcfj1f/njieCC7STbAB1sKkrR/hbGU7IOPxVDjT5eUxqWrQche8w4+AG8pVkBOdaC3pjq5Jqa6h1Dom+Rnf02vhnEKawibmfqZTjrY434RL5/E4nnb5aaGMYfpENvX1xcE2tm+RhUchQubThQwadB2aFYG7brDrx7Q9QPoJcFqNy/AbFVIR0pgO0ZJ8utZu6BEGAUdyI/LGek=
