version: '2.1'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=migrate
      - MYSQL_USER=migrate
      - MYSQL_PASSWORD=migrate
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - "3306"
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        hack_user: develop
        hack_group: develop
    env_file: .env
    environment:
      - DB_HOSTNAME=db
      - DB_DATABASE=migrate
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_PORT=3306
    user: develop
    tty: true
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    links:
      - db
    depends_on:
      - db
