#!/usr/bin/env python

from subprocess import call
from sys import exit
from argparse import ArgumentParser
import os

TYPECHECK_PROGRAM = 'hh_client'
FORMATTER_PROGRAM = 'hh_format'

def find_all_files(directory):
  for root, dirs, files in os.walk(directory):
    for file in files:
      if file.endswith('.hh'):
        yield os.path.join(root, file)

if __name__ == '__main__':
  parser = ArgumentParser(description='Development tool for Hack')
  parser.add_argument('command', metavar='COMMAND', type=str, help='Command name')

  args = parser.parse_args()

  if args.command == 'check':
    call([ 'touch', '.hhconfig' ])
    call([ TYPECHECK_PROGRAM, 'check' ])
  elif args.command == 'format':
    # FIXME: KISS!!
    for fname in find_all_files('./src'):
      call([ FORMATTER_PROGRAM, fname, '-i' ])
    for fname in find_all_files('./test'):
      call([ FORMATTER_PROGRAM, fname, '-i' ])
    for fname in find_all_files('./bin'):
      call([ FORMATTER_PROGRAM, fname, '-i' ])
